### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.oblador.performance.StartTimeProvider"

### ISSUE THREAD

**Issue by riteshakya037** [saibotma/jitsi_meet_wrapper#112]
I'm running into a problem when trying to add this library into my project. 

E/AndroidRuntime(17425): java.lang.RuntimeException: Unable to get provider com.oblador.performance.StartTimeProvider: java.lang.ClassNotFoundException: Didn't find class "com.oblador.performance.StartTimeProvider" on path: DexPathList[[zip file "/data/app/~~nMxs153_VYNYAkrp5uTW8g==/ai.cerulearn.debug-FedVJ4j52pJvHHXu6QsbnA==/base.apk"],nativeLibraryDirectories=[/data/app/~~nMxs153_VYNYAkrp5uTW8g==/ai.cerulearn.debug-FedVJ4j52pJvHHXu6QsbnA==/lib/arm64, /data/app/~~nMxs153_VYNYAkrp5uTW8g==/ai.cerulearn.debug-FedVJ4j52pJvHHXu6QsbnA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(17425): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7493)
E/AndroidRuntime(17425): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
E/AndroidRuntime(17425): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
E/AndroidRuntime(17425): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime(17425): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
E/AndroidRuntime(17425): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17425): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17425): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17425): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(17425): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17425): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17425): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(17425): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oblador.performance.StartTimeProvider" on path: DexPathList[[zip file "/data/app/~~nMxs153_VYNYAkrp5uTW8g==/ai.cerulearn.debug-FedVJ4j52pJvHHXu6QsbnA==/base.apk"],nativeLibraryDirectories=[/data/app/~~nMxs153_VYNYAkrp5uTW8g==/ai.cerulearn.debug-FedVJ4j52pJvHHXu6QsbnA==/lib/arm64, /data/app/~~nMxs153_VYNYAkrp5uTW8g==/ai.cerulearn.debug-FedVJ4j52pJvHHXu6QsbnA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(17425): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(17425): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(17425): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(17425): 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
E/AndroidRuntime(17425): 	at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
E/AndroidRuntime(17425): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7477)
E/AndroidRuntime(17425): 	... 11 more

**Comment by RealSarkhan** [comment]
I have the same issue, it happens in every sdk versions after 7.0.1 
Note: I'm trying to use the sdk in flutter plugin.

**Comment by saibotma** [comment]
Please try the newest version. If it still does not work, please provide a fully reproducible example.

**Comment by RealSerkhan** [comment]
@saibotma I tested on the latest version, I'm getting the same result. My android version is 13. and getting the exactly the same error with @riteshakya037 shared

**Comment by saibotma** [comment]
Please share a reproducible example.

**Comment by riteshakya037** [comment]
@RealSarkhan @saibotma I apologize for the delay in my response. I was away and didn't have a chance to reply earlier.

Regarding the issue,  a solution that worked for me was copying the ProGuard rules from the given [link](https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro) and adding the ProGuard file to the release mode in the app/build.gradle file. Not really sure why that would work for the debug version of the app as well.

```
android {
    // ...
    buildTypes {
        // ...
        release {
            // ...
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

If you have any further questions or need additional assistance, please let me know. I'm here to help!

**Comment by raulsuro** [comment]
Hello @RealSarkhan and @riteshakya037 I am facing the same issue and the solution you propose is not working on my case. I have tried with multiple versions after 7.0.1 and adding different configurations to the Proguard file but still getting:

`java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.d: java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiInitializer`

**Comment by niravkakadiya25** [comment]
Hello @saibotma @riteshakya037 
This issue is working for me.
just update the classpath of the project.

project-level build Gradle:-
classpath 'com.android.tools.build:gradle:7.1.2'

**Comment by raulsuro** [comment]
Thanks! @niravkakadiya25 I could make it run without crashes now I am just trying to join a meeting and I am getting this error:
```initializing RN with Activity
12:07:53.220  E  Failed to set cxx error hanlder function
                 java.lang.NoSuchMethodException: a6.i.handleCxxError [class java.lang.Exception]
                 	at java.lang.Class.getMethod(Class.java:2103)
                 	at java.lang.Class.getMethod(Class.java:1724)
                 	at a6.i.d0(:391)
                 	at a6.i.<init>(:304)
                 	at a6.k.b(:358)
                 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(:256)
                 	at org.jitsi.meet.sdk.JitsiMeetView.initialize(:202)
                 	at org.jitsi.meet.sdk.JitsiMeetView.<init>(:103)
                 	at java.lang.reflect.Constructor.newInstance0(Native Method)
                 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
                 	at e.e.B(:706)
                 	at androidx.appcompat.app.b.setContentView(:195)
                 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(:103)```
                 	
                 	but I guess this is not related. 
                 	Thanks again!

**Comment by niravkakadiya25** [comment]
can you share join meeting code as well

**Comment by raulsuro** [comment]
sure @niravkakadiya25 :

```kotlin
   private fun joinMeeting(call: MethodCall, result: Result) {
//        val room = call.argument<String>("room")
        val room="eff9383f-afd6-41a3-ae17-d13d12747a28"

//        if (room.isNullOrBlank()) {
//            result.error("400",
//                    "room can not be null or empty",
//                    "room can not be null or empty")
//            return
//        }

        Log.d(JITSI_PLUGIN_TAG, "Joining Room: $room")

        val bundle = Bundle()
        bundle.putString("displayName", call.argument("sstudent46@yopmail.com"))
        bundle.putString("email", call.argument("sstudent46@yopmail.com"))
//        userInfo.displayName = call.argument("sstudent46@yopmail.com")
//        userInfo.email = call.argument("sstudent46@yopmail.com")
        if (call.argument<String?>("userAvatarURL") != null) {
            bundle.putString("avatarURL", call.argument("userAvatarURL"))

//            userInfo.avatar = URL(call.argument("userAvatarURL"))
        }
        Log.i("JitsiMeetPlugin", "--joinMeeting: ${jitsiInitializer.toString()}")
        val userInfo = JitsiMeetUserInfo(bundle)

//        userInfo.avatar = URL("https://lms-tal3eem.test.env.creativeadvtech.ml/static/images/profiles/default_50.3455a6581573.png")


//        var serverURLString = call.argument<String>("serverURL")
        var serverURLString="https://jitsi.dev.creativeadvtech.ml"
        if (serverURLString == null) {
            serverURLString = "https://meet.jit.si";
        }
        val serverURL = URL(serverURLString)
        Log.d(JITSI_PLUGIN_TAG, "Server URL: $serverURL, $serverURLString")

        val optionsBuilder = JitsiMeetConferenceOptions.Builder()

        // Set meeting options
        optionsBuilder
                .setServerURL(serverURL)
                .setRoom(room)
                .setSubject(call.argument("subject"))
                .setToken("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsibmFtZSI6InNzdHVkZW50NEB5b3BtYWlsLmNvbSIsImVtYWlsIjoic3N0dWRlbnQ0QHlvcG1haWwuY29tIiwiYWZmaWxpYXRpb24iOiJtZW1iZXIifX0sInN1YiI6Imh0dHBzOi8vaml0c2kuZGV2LmNyZWF0aXZlYWR2dGVjaC5tbCIsImlzcyI6InRhM2xlZW1lZHhhcHAiLCJhdWQiOiJ0YTNsZWVtZWR4YXBwIiwicm9vbSI6ImJmZmYwZDc0LWQzNmMtNGRjZC1hZmM3LWVhNWM5ZmVkZDM1ZSIsImlhdCI6MTY4NjEzMDA4N30.Mx-lOWMghL_NNHn9WuJebovyCdeIOQ94zBDjh9O_gGQ"
                )
                .setAudioMuted(call.argument("audioMuted") ?: false)
                .setAudioOnly(call.argument("audioOnly") ?: false)
                .setVideoMuted(call.argument("videoMuted") ?: false)
                .setUserInfo(userInfo)

        // Add feature flags into options, reading given Map
        if (call.argument<HashMap<String, Any>?>("featureFlags") != null) {
            val featureFlags = call.argument<HashMap<String, Any>>("featureFlags")
            featureFlags!!.forEach { (key, value) ->
                if (value is Boolean) {
                    val boolVal = value.toString().toBoolean()
                    optionsBuilder.setFeatureFlag(key, boolVal)
                } else {
                    val intVal = value.toString().toInt()
                    optionsBuilder.setFeatureFlag(key, intVal)
                }
            }
        }

        // Build with meeting options and feature flags
        val options = optionsBuilder.build()

        JitsiMeetPluginActivity.launchActivity(activity, options)
        result.success("Successfully joined room: $room")
    }
```

**Comment by niravkakadiya25** [comment]
have you added proguards?

**Comment by raulsuro** [comment]
Yes @niravkakadiya25  proguard adding all related to jitsi:
`-keep class org.jitsi.meet.** { *; }
-keep class org.jitsi.meet.sdk.** { *; }`

and enabled multidex
Still getting the same error after joining meeting I can see the room but then when I finally try to join it gives me that error

**Comment by niravkakadiya25** [comment]
#=== Flutter Wrapper ===#
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

#=== Jitsi ===#
# Source: https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro
# Check above link for changes if release builds are broken again

# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# React Native

# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers,includedescriptorclasses class * { native <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }

-dontwarn com.facebook.react.**
-keep,includedescriptorclasses class com.facebook.react.bridge.** { *; }

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-keep class okio.** { *; }
-dontwarn okio.**

# WebRTC

-keep class org.webrtc.** { *; }
-dontwarn org.chromium.build.BuildHooksAndroid

# Jisti Meet SDK

-keep class org.jitsi.meet.** { *; }
-keep class org.jitsi.meet.sdk.** { *; }

# We added the following when we switched minifyEnabled on. Probably because we
# ran the app and hit problems...

-keep class com.facebook.react.bridge.CatalystInstanceImpl { *; }
-keep class com.facebook.react.bridge.ExecutorToken { *; }
-keep class com.facebook.react.bridge.JavaScriptExecutor { *; }
-keep class com.facebook.react.bridge.ModuleRegistryHolder { *; }
-keep class com.facebook.react.bridge.ReadableType { *; }
-keep class com.facebook.react.bridge.queue.NativeRunnable { *; }
-keep class com.facebook.react.devsupport.** { *; }

-dontwarn com.facebook.react.devsupport.**
-dontwarn com.google.appengine.**
-dontwarn com.squareup.okhttp.**
-dontwarn javax.servlet.**

# ^^^ We added the above when we switched minifyEnabled on.

# Rule to avoid build errors related to SVGs.
-keep public class com.horcrux.svg.** {*;}

# Hermes
-keep class com.facebook.hermes.unicode.** { *; }


@raulsuro  try to add this proguards

**Comment by raulsuro** [comment]
@niravkakadiya25  thanks but I am still getting the same error. Could be proguard or maybe some library that needs update. Still investigating

**Comment by niravkakadiya25** [comment]
I think you need to use latest version of jitsee @raulsuro

**Comment by raulsuro** [comment]
I am using this one:
   
    implementation ('org.jitsi.react:jitsi-meet-sdk:8.1.2') { transitive = true }
    
    Actually these issues started when I updated to the latest version.
    @niravkakadiya25
