### ISSUE TITLE
Jitsi_meet_wrapper crashes with flutter_stripe

### ISSUE THREAD

**Issue by mbebs** [saibotma/jitsi_meet_wrapper#118]
Jitsi_meet_wrapper crashes if the flutter_stripe dependency is added. Without the flutter_stripe dependency, jitsi_meet_wrapper works with no issues. Below is errors

`D/ReactInstanceManagerHolder(28424): initializing RN with Activity
D/AndroidRuntime(28424): Shutting down VM
E/AndroidRuntime(28424): FATAL EXCEPTION: main
E/AndroidRuntime(28424): Process: com.zabtel.njangi, PID: 28424
E/AndroidRuntime(28424): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~DVwcobJ_5v53qTVM-P-ESA==/com.zabtel.njangi-2hp7u0MQWNoXC1yia3aPIA==/base.apk!classes14.dex)
E/AndroidRuntime(28424): 	at com.facebook.react.ReactAndroidHWInputDeviceHelper.<clinit>(ReactAndroidHWInputDeviceHelper.java:25)
E/AndroidRuntime(28424): 	at com.facebook.react.ReactRootView.<init>(ReactRootView.java:100)
E/AndroidRuntime(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:181)
E/AndroidRuntime(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:224)
E/AndroidRuntime(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:157)
E/AndroidRuntime(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/AndroidRuntime(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/AndroidRuntime(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/AndroidRuntime(28424): 	at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
E/AndroidRuntime(28424): 	at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(28424): 	at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(28424): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(28424): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(28424): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(28424): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(28424): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(28424): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(28424): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(28424): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28424): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(28424): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(28424): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28424): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(28424): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(28424): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(28424): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~DVwcobJ_5v53qTVM-P-ESA==/com.zabtel.njangi-2hp7u0MQWNoXC1yia3aPIA==/base.apk!classes14.dex)
E/JitsiMeetSDK(28424): 	at com.facebook.react.ReactAndroidHWInputDeviceHelper.<clinit>(ReactAndroidHWInputDeviceHelper.java:25)
E/JitsiMeetSDK(28424): 	at com.facebook.react.ReactRootView.<init>(ReactRootView.java:100)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:181)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:224)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:157)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/JitsiMeetSDK(28424): 	at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
E/JitsiMeetSDK(28424): 	at android.app.Activity.performCreate(Activity.java:8000)
E/JitsiMeetSDK(28424): 	at android.app.Activity.performCreate(Activity.java:7984)
E/JitsiMeetSDK(28424): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/JitsiMeetSDK(28424): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/JitsiMeetSDK(28424): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(28424): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/JitsiMeetSDK(28424): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(28424): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(28424): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(28424): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(28424): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(28424): 
E/JitsiMeetSDK(28424): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~DVwcobJ_5v53qTVM-P-ESA==/com.zabtel.njangi-2hp7u0MQWNoXC1yia3aPIA==/base.apk!classes14.dex)
E/JitsiMeetSDK(28424): 	at com.facebook.react.ReactAndroidHWInputDeviceHelper.<clinit>(ReactAndroidHWInputDeviceHelper.java:25)
E/JitsiMeetSDK(28424): 	at com.facebook.react.ReactRootView.<init>(ReactRootView.java:100)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:181)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:224)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:157)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/JitsiMeetSDK(28424): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/JitsiMeetSDK(28424): 	at dev.saibotma.jitsi_meet_wrapper.JitsiMeetWrapperActivity.onCreate(JitsiMeetWrapperActivity.kt:37)
E/JitsiMeetSDK(28424): 	at android.app.Activity.performCreate(Activity.java:8000)
E/JitsiMeetSDK(28424): 	at android.app.Activity.performCreate(Activity.java:7984)
E/JitsiMeetSDK(28424): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/JitsiMeetSDK(28424): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/JitsiMeetSDK(28424): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(28424): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/JitsiMeetSDK(28424): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(28424): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(28424): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(28424): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(28424): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(28424): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)'

Below are the dependencies that don't work together:
flutter_stripe: ^9.0.0+1
jitsi_meet_wrapper: ^0.2.0+1

**Comment by sha3rawi33** [comment]
Same issue

**Comment by xrhstos334** [comment]
Same issue

**Comment by TetrixGauss** [comment]
Hello guys i have the answer to that i suppose! If jitsi or stripe could change the classes names under the facebook/bridge directory it works fine! The problem is that both packages and actually any jitsi or stripe package use the same code for facebook/bridge directory which is very odd! anyway! if you want i have forked and changed the stripe_android files and now any jitsi package can work with my fork.
Give it a try if you want and send me your feedback please!

https://github.com/TetrixGauss/flutter_stripe.git

I hope this works for you as well!

**Comment by mbebs** [comment]
Thank you so much for the workaround. But how do I reference and import it? I see you changed the package name to stripe_workspace.
________________________________

**Comment by mbebs** [comment]
> Hello guys i have the answer to that i suppose! If jitsi or stripe could change the classes names under the facebook/bridge directory it works fine! The problem is that both packages and actually any jitsi or stripe package use the same code for facebook/bridge directory which is very odd! anyway! if you want i have forked and changed the stripe_android files and now any jitsi package can work with my fork. Give it a try if you want and send me your feedback please!
> 
> https://github.com/TetrixGauss/flutter_stripe.git
> 
> I hope this works for you as well!

Thank you so much for this workaround. I tried it but it is not working... No more crashes but the stripe is not working. Just getting exception below:
`'StripeConfigException' is not a subtype of type 'String'`

**Comment by TetrixGauss** [comment]
Can you please open an issue on my repo and put there the whole console log with the error?

**Comment by mbebs** [comment]
Issue was my mistake.  It's working...thanks so much for this fix...



Sent from my T-Mobile 5G Device



-------- Original message --------
From: TetrixGauss ***@***.***>
Date: 9/10/23 3:24 AM (GMT-06:00)
To: saibotma/jitsi_meet_wrapper ***@***.***>
Cc: mbebwo ***@***.***>, Author ***@***.***>
Subject: Re: [saibotma/jitsi_meet_wrapper] Jitsi_meet_wrapper crashes with flutter_stripe (Issue #118)


Can you please open an issue on my repo and put there the whole console log with the error?

**Comment by TetrixGauss** [comment]
Glad I could help!

**Comment by Korefey** [comment]
@TetrixGauss Can you help me with error. I user your library an get an error
* What went wrong:
```
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not create task ':stripe_android:generateReleaseLintModel'.
      > coreLibraryDesugaring configuration contains no dependencies. If you intend to enable core library desugaring, please add dependencies to coreLibraryDesugaring configuration.
```

**Comment by TetrixGauss** [comment]
> @TetrixGauss Can you help me with error. I user your library an get an error
> * What went wrong:
> ```
> Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
>    > Could not create task ':stripe_android:generateReleaseLintModel'.
>       > coreLibraryDesugaring configuration contains no dependencies. If you intend to enable core library desugaring, please add dependencies to coreLibraryDesugaring configuration.
> ```
> 

Can you give me more information please to reproduce the error?

**Comment by Korefey** [comment]
> > @TetrixGauss Can you help me with error. I user your library an get an error
> > 
> > * What went wrong:
> > 
> > ```
> > Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> > > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
> >    > Could not create task ':stripe_android:generateReleaseLintModel'.
> >       > coreLibraryDesugaring configuration contains no dependencies. If you intend to enable core library desugaring, please add dependencies to coreLibraryDesugaring configuration.
> > ```
> 
> Can you give me more information please to reproduce the error?

Sorry - this bug was in my fork librery.
When I used your, I get another error 
* What went wrong:
Execution failed for task ':stripe_android:compileReleaseKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (1.8) and 'compileReleaseKotlin' (17).

**Comment by TetrixGauss** [comment]
> > > @TetrixGauss Can you help me with error. I user your library an get an error
> > > 
> > > * What went wrong:
> > > 
> > > ```
> > > Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> > > > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
> > >    > Could not create task ':stripe_android:generateReleaseLintModel'.
> > >       > coreLibraryDesugaring configuration contains no dependencies. If you intend to enable core library desugaring, please add dependencies to coreLibraryDesugaring configuration.
> > > ```
> > 
> > Can you give me more information please to reproduce the error?
> 
> @TetrixGauss Sorry - this bug was in my fork library.
> When I used your library - I get another error 
> 
> Execution failed for task ':stripe_android:compileReleaseKotlin'.
> > Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (1.8) and 'compileReleaseKotlin' (17).
> 
> 

Can you give me all the configuration? Gradle files etc.

**Comment by Korefey** [comment]
@TetrixGauss Sure
[Desktop.zip](https://github.com/saibotma/jitsi_meet_wrapper/files/15192376/Desktop.zip)

**Comment by TetrixGauss** [comment]
@Korefey It looks like you're trying to compile Java code with Java 8 (compileReleaseJavaWithJavac) and Kotlin code with a higher version (JVM 17). To fix this, you need to ensure that the Java version used for both tasks is consistent.

Here's what you can do:

1. **Check Kotlin configuration:** Make sure that the Kotlin plugin is configured to use Java 8 or lower. You can set the JVM target version for Kotlin in your Gradle or Maven configuration.
2. **Update Java version for Java tasks:** If possible, update the Java version for your Java tasks (compileReleaseJavaWithJavac) to match the Kotlin version. You can set the Java version in your build.gradle or build.gradle.kts file.For Gradle, you can set the Java version like this:

```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
```
Ensure that JavaVersion.VERSION_17 matches the Kotlin JVM target version.
3. **Check dependencies:** Ensure that your project dependencies are compatible with the Java version you're using. Sometimes, third-party libraries might require a specific Java version.
4. **Update Kotlin version**: If necessary, update your Kotlin version to match the Java version you're using. Ensure that your Kotlin version supports the Java version you're targeting.
5. **Sync Gradle/Maven:** After making changes to your configuration, sync your Gradle or Maven project to apply the changes.

**Comment by TetrixGauss** [comment]
@Korefey are you ok? Should I close that issue?

**Comment by Korefey** [comment]
@TetrixGauss yes, I solved this problem.

**Comment by saibotma** [comment]
You guys can try using the new official package: https://pub.dev/packages/jitsi_meet_flutter_sdk
