### ISSUE TITLE
java.nio.FloatBuffer JitsiMeetUncaughtExceptionHandler FATAL ERROR

### ISSUE THREAD

**Issue by AbdouEsi** [saibotma/jitsi_meet_wrapper#77]
Hi 

i had this error when start video or start share screen : 

E/JitsiMeetSDK(28683): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(28683): java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/FloatBuffer; in class Ljava/nio/FloatBuffer; or its super classes (declaration of 'java.nio.FloatBuffer' appears in /system/framework/core-oj.jar)
E/JitsiMeetSDK(28683): 	at org.webrtc.GlUtil.createFloatBuffer(GlUtil.java:47)
E/JitsiMeetSDK(28683): 	at org.webrtc.GlGenericDrawer.<clinit>(GlGenericDrawer.java:75)
E/JitsiMeetSDK(28683): 	at org.webrtc.YuvConverter.<init>(YuvConverter.java:111)

**Comment by saibotma** [comment]
Hey there,

please try the newest release and create a reproducible example if it still does not work.
