### ISSUE TITLE
isNotificationsEnabled feature flag not working

### ISSUE THREAD

**Issue by shabanov-krl** [saibotma/jitsi_meet_wrapper#83]
set  `FeatureFlag.isNotificationsEnabled: false`, but notification delivered
![image](https://user-images.githubusercontent.com/46450095/221499692-c0843503-59d6-451b-9d83-d1ad64fdf2aa.png)

**Comment by shabanov-krl** [comment]
logs when tapped push

```
I/JitsiMeetSDK(20789): PictureInPicture Entering Picture-in-Picture
E/JitsiMeetSDK(20789): Failed to enter PiP mode
E/JitsiMeetSDK(20789): java.lang.RuntimeException: Failed to enter Picture-in-Picture
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.PictureInPictureModule.enterPictureInPicture(PictureInPictureModule.java:113)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetView.enterPictureInPicture(JitsiMeetView.java:141)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onUserLeaveHint(JitsiMeetActivity.java:286)
E/JitsiMeetSDK(20789): 	at android.app.Activity.performUserLeaving(Activity.java:8497)
E/JitsiMeetSDK(20789): 	at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1628)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:4978)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4958)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/JitsiMeetSDK(20789): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/JitsiMeetSDK(20789): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(20789): 
E/JitsiMeetSDK(20789): java.lang.RuntimeException: Failed to enter Picture-in-Picture
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.PictureInPictureModule.enterPictureInPicture(PictureInPictureModule.java:113)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetView.enterPictureInPicture(JitsiMeetView.java:141)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onUserLeaveHint(JitsiMeetActivity.java:286)
E/JitsiMeetSDK(20789): 	at android.app.Activity.performUserLeaving(Activity.java:8497)
E/JitsiMeetSDK(20789): 	at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1628)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:4978)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4958)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/JitsiMeetSDK(20789): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/JitsiMeetSDK(20789): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/OrientationModule(20789): onActivityPaused
D/OrientationModule(20789): onActivityCreated
D/OrientationModule(20789): onActivityStarted
D/OrientationModule(20789): onActivityResumed
W/unknown:ReactContext(20789): initializeMessageQueueThreads() is called.
I/ReactNativeJS(20789): Running "App
W/Parcel  (20789): Expecting binder but got null!
D/EGL_emulation(20789): app_time_stats: avg=3664.45ms min=12.76ms max=10906.86ms count=3
I/ReactNative(20789): [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{e048e32 V.E...... .......D 0,0-1080,2088 #b}
I/JitsiMeetSDK(20789): [features/video-quality] Video quality level for thumbnail height: 185, is: 180, override: false, max full res N: 2
E/JitsiMeetSDK(20789): [features/base/app] Error(TypeError){"message":"undefined is not an object (evaluating 'this.props.flags[r(d[18]).CALL_INTEGRATION_ENABLED]')","stack":"index.android.bundle:736:8728\nf@index.android.bundle:736:1582\nindex.android.bundle:736:1331\nf@index.android.bundle:736:1582\no@index.android.bundle:736:1997\nindex.android.bundle:736:2140\nu@index.android.bundle:85:157\nindex.android.bundle:85:866\nindex.android.bundle:92:1662\nk@index.android.bundle:92:498\nw@index.android.bundle:92:888\ncallReactNativeMicrotasks@index.android.bundle:92:3055\nvalue@index.android.bundle:45:2868\nindex.android.bundle:45:960\nvalue@index.android.bundle:45:2504\nvalue@index.android.bundle:45:919\nvalue@[native code]\nvalue@[native code]"}
E/JitsiMeetSDK(20789): Error running onHostPause, ignoring
E/JitsiMeetSDK(20789): java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetWrapperActivity Paused activity: JitsiMeetWrapperActivity
E/JitsiMeetSDK(20789): 	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
E/JitsiMeetSDK(20789): 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:603)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:120)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onStop(JitsiMeetActivity.java:120)
E/JitsiMeetSDK(20789): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1584)
E/JitsiMeetSDK(20789): 	at android.app.Activity.performStop(Activity.java:8527)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5170)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5150)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5215)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/JitsiMeetSDK(20789): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/JitsiMeetSDK(20789): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/JitsiMeetSDK(20789): 
E/JitsiMeetSDK(20789): java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: JitsiMeetWrapperActivity Paused activity: JitsiMeetWrapperActivity
E/JitsiMeetSDK(20789): 	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
E/JitsiMeetSDK(20789): 	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:603)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetActivityDelegate.onHostPause(JitsiMeetActivityDelegate.java:120)
E/JitsiMeetSDK(20789): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onStop(JitsiMeetActivity.java:120)
E/JitsiMeetSDK(20789): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1584)
E/JitsiMeetSDK(20789): 	at android.app.Activity.performStop(Activity.java:8527)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5170)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5150)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5215)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/JitsiMeetSDK(20789): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/JitsiMeetSDK(20789): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(20789): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(20789): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/JitsiMeetSDK(20789): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(20789): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/OrientationModule(20789): onActivityStopped
D/OrientationModule(20789): onActivitySaveInstanceState
I/JitsiMeetSDK(20789): [features/video-quality] Video quality level for thumbnail height: -11, is: 180, override: false, max full res N: 2
I/JitsiMeetSDK(20789): Using AudioDeviceHandlerGeneric as the audio device handler
I/JitsiMeetSDK(20789): [features/base/net-info] Network changed {"isOnline":true,"details":{"isConnectionExpensive":false,"subnet":"255.255.255.255","ipAddress":"10.0.2.16","frequency":2447,"strength":99,"bssid":"02:00:00:00:00:00"},"networkType":"wifi"}
I/JitsiMeetSDK(20789): AudioDeviceHandlerGeneric Available audio devices: [SPEAKER]
I/JitsiMeetSDK(20789): AudioMode Update audio route for mode: 2
D/JitsiMeetSDK(20789): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
D/JitsiMeetSDK(20789): AudioDeviceHandlerGeneric Audio devices added
I/JitsiMeetSDK(20789): [features/app] appNavigate to https://meet.jit.si
I/JitsiMeetSDK(20789): [features/base/connection] No connection found while disconnecting.
I/JitsiMeetSDK(20789): AudioMode Selected audio device: SPEAKER
D/AudioManager(20789): dispatching onAudioFocusChange(-1) to android.media.AudioManager@142360corg.jitsi.meet.sdk.AudioDeviceHandlerGeneric@ef0db55
D/JitsiMeetSDK(20789): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
W/JitsiMeetSDK(20789): [modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
I/JitsiMeetSDK(20789): [features/analytics] Initialized 0 analytics handlers
I/JitsiMeetSDK(20789): [features/base/media] Start muted: 
D/JitsiMeetSDK(20789): ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK(20789): [features/base/media] Start audio only set to false
D/JitsiMeetSDK(20789): ExternalAPI Sending event: READY_TO_CLOSE with data: { NativeMap: {} }
I/JitsiMeetSDK(20789): [features/app] Loaded SDK undefined
I/JitsiMeetSDK(20789): SDK is ready to close
I/JitsiMeetSDK(20789): SDK is ready to close
I/JitsiMeetSDK(20789): [features/video-quality] Video quality level for thumbnail height: -11, is: 180, override: false, max full res N: 2
I/JitsiMeetSDK(20789): [features/video-quality] Video quality level for thumbnail height: 185, is: 180, override: false, max full res N: 2
D/OrientationModule(20789): onActivityDestroyed
D/OrientationModule(20789): onActivityPaused
D/OrientationModule(20789): onActivityStarted
D/OrientationModule(20789): onActivityResumed
E/SurfaceSyncer(20789): Failed to find sync for id=0
E/SurfaceSyncer(20789): Failed to find sync for id=1
I/JitsiMeetSDK(20789): AudioDeviceHandlerGeneric Available audio devices: [SPEAKER]
I/JitsiMeetSDK(20789): AudioMode Update audio route for mode: 2
D/EGL_emulation(20789): app_time_stats: avg=16.79ms min=3.97ms max=148.01ms count=43
I/JitsiMeetSDK(20789): AudioMode Selected audio device: SPEAKER
W/JitsiMeetSDK(20789): [features/calendar-sync] Calendar access not granted.
D/JitsiMeetSDK(20789): [modules/RTC/RTCUtils.js] Available devices:  [ { kind: 'videoinput',
D/JitsiMeetSDK(20789):     label: '0',
D/JitsiMeetSDK(20789):     deviceId: '0',
D/JitsiMeetSDK(20789):     groupId: '',
D/JitsiMeetSDK(20789):     facing: 'environment' },
D/JitsiMeetSDK(20789):   { kind: 'videoinput',
D/JitsiMeetSDK(20789):     label: '1',
D/JitsiMeetSDK(20789):     deviceId: '1',
D/JitsiMeetSDK(20789):     groupId: '',
D/JitsiMeetSDK(20789):     facing: 'front' },
D/JitsiMeetSDK(20789):   { kind: 'audioinput',
D/JitsiMeetSDK(20789):     label: 'Audio',
D/JitsiMeetSDK(20789):     groupId: '',
D/JitsiMeetSDK(20789):     deviceId: 'audio-1' } ]
I/JitsiMeetSDK(20789): [features/app] appNavigate to undefined
I/JitsiMeetSDK(20789): [features/video-quality] Video quality level for thumbnail height: 185, is: 180, override: false, max full res N: 2
D/JitsiMeetSDK(20789): [modules/connectivity/TrackStreamingStatus.ts] Figure out conn status for 8b12c6c2-v0, is video muted: true video track frozen: false p2p mode: false is in forwarded sources: true currentStatus => newStatus: active => active
D/JitsiMeetSDK(20789): [modules/RTC/JitsiRemoteTrack.js] Disposing track streaming status: 8b12c6c2-v0
D/JitsiMeetSDK(20789): [modules/connectivity/TrackStreamingStatus.ts] Figure out conn status for 9648ea3c-v0, is video muted: true video track frozen: false p2p mode: false is in forwarded sources: true currentStatus => newStatus: active => active
D/JitsiMeetSDK(20789): [modules/RTC/JitsiRemoteTrack.js] Disposing track streaming status: 9648ea3c-v0
D/JitsiMeetSDK(20789): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
W/JitsiMeetSDK(20789): [modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
I/JitsiMeetSDK(20789): [features/analytics] Initialized 0 analytics handlers
I/JitsiMeetSDK(20789): [features/base/media] Start muted: 
D/JitsiMeetSDK(20789): ExternalAPI Sending event: AUDIO_MUTED_CHANGED with data: { NativeMap: {"muted":false} }
D/JitsiMeetSDK(20789): ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK(20789): [features/base/media] Start audio only set to false
I/JitsiMeetSDK(20789): [features/app] appNavigate to undefined
I/JitsiMeetSDK(20789): [features/base/connection] No connection found while disconnecting.
D/JitsiMeetSDK(20789): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
W/JitsiMeetSDK(20789): [modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
I/JitsiMeetSDK(20789): [features/analytics] Initialized 0 analytics handlers
I/JitsiMeetSDK(20789): [features/base/media] Start muted: 
D/JitsiMeetSDK(20789): ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK(20789): [features/base/media] Start audio only set to false
I/JitsiMeetSDK(20789): [modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Closing peerconnection
I/JitsiMeetSDK(20789): [features/app] appNavigate to undefined
D/JitsiMeetSDK(20789): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
W/JitsiMeetSDK(20789): [modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
I/JitsiMeetSDK(20789): [features/analytics] Initialized 0 analytics handlers
I/JitsiMeetSDK(20789): [features/base/media] Start muted: 
D/JitsiMeetSDK(20789): ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK(20789): [features/base/media] Start audio only set to false
I/org.webrtc.Logging(20789): WebRtcAudioRecordExternal: stopRecording
I/org.webrtc.Logging(20789): WebRtcAudioRecordExternal: stopThread
I/JitsiMeetSDK(20789): [features/app] appNavigate to undefined
I/JitsiMeetSDK(20789): [features/base/connection] No connection found while disconnecting.
D/JitsiMeetSDK(20789): [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
W/JitsiMeetSDK(20789): [modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
I/JitsiMeetSDK(20789): [features/analytics] Initialized 0 analytics handlers
I/JitsiMeetSDK(20789): [features/base/media] Start muted: 
D/JitsiMeetSDK(20789): ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK(20789): [features/base/media] Start audio only set to false
I/JitsiMeetSDK(20789): [modules/xmpp/xmpp.js] (TIME) Strophe disconnecting:	 67828625.140149
W/JitsiMeetSDK(20789): [modules/xmpp/strophe.util.js] Strophe: Disconnect was called because: undefined
W/ReactNativeJS(20789): EventEmitter.removeListener('appStateDidChange', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
I/org.webrtc.Logging(20789): WebRtcAudioRecordExternal: doAudioRecordStateCallback: STOP
I/org.webrtc.Logging(20789): WebRtcAudioEffectsExternal: release
I/org.webrtc.Logging(20789): WebRtcAudioRecordExternal: releaseAudioResources
W/ReactNativeJS(20789): EventEmitter.removeListener('@@IMMERSIVE_STATE_CHANGED', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
I/org.webrtc.Logging(20789): CameraCapturer: Stop capture
I/org.webrtc.Logging(20789): CameraCapturer: Stop capture: No session open
I/org.webrtc.Logging(20789): CameraCapturer: Stop capture done
I/org.webrtc.Logging(20789): CameraCapturer: dispose
I/org.webrtc.Logging(20789): CameraCapturer: Stop capture
I/org.webrtc.Logging(20789): CameraCapturer: Stop capture: No session open
I/org.webrtc.Logging(20789): CameraCapturer: Stop capture done
I/org.webrtc.Logging(20789): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(20789): SurfaceTextureHelper: dispose()
I/org.webrtc.Logging(20789): GlShader: Deleting shader.
I/JitsiMeetSDK(20789): AudioMode Update audio route for mode: 0
D/com.oney.WebRTCModule.WebRTCModule(20789): PeerConnection.close() for 0
W/JitsiMeetSDK(20789): [features/base/sounds] PLAY_SOUND: no sound found for id: PARTICIPANT_LEFT_SOUND
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: stopPlayout
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: underrun count: 0
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: stopThread
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: Stopping the AudioTrackThread...
V/MediaPlayer(20789): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(20789): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(20789): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(20789): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: AudioTrackThread has now been stopped.
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: Calling AudioTrack.stop...
D/AudioTrack(20789): stop(100): called with 936000 frames delivered
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: AudioTrack.stop is done.
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: doAudioTrackStateCallback: 1
I/org.webrtc.Logging(20789): WebRtcAudioTrackExternal: releaseAudioResources
V/MediaPlayer(20789): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(20789): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(20789): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(20789): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/org.webrtc.Logging(20789): NetworkMonitor: Stop monitoring with native observer 135410421580336
I/org.webrtc.Logging(20789): NetworkMonitorAutoDetect: Unregister network callback
D/com.oney.WebRTCModule.VideoTrackAdapter(20789): Deleted adapter for mixedlabelvideo0
D/com.oney.WebRTCModule.VideoTrackAdapter(20789): Deleted adapter for 882D01A4-1DD0-46FA-BFA3-9FDD09535C1E-13
D/com.oney.WebRTCModule.VideoTrackAdapter(20789): Deleted adapter for 34ddeebe-2711-41ff-aab6-d09a3441c377-4
D/com.oney.WebRTCModule.WebRTCModule(20789): mediaStreamRelease() stream is null
D/com.oney.WebRTCModule.WebRTCModule(20789): mediaStreamRelease() stream is null
V/MediaPlayer(20789): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(20789): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

**Comment by coderof19clc7** [comment]
did you solve it ?

**Comment by shabanov-krl** [comment]
> @shabanov-krl did you solve it ?

no

**Comment by saibotma** [comment]
Hey there,

please try the newest release and create a reproducible example if it still does not work.
